# OPTIONS shows allowed methods.
OPTIONS http://localhost:3030/api/auth/login

### Login
POST http://localhost:3030/api/auth/login
Content-Type: application/json

{
    "email": "admin@onvs.fr",
    "password": "test"
}

### Not allowed methods.
GET http://localhost:3030/api/auth/login


### Show user
GET http://localhost:3030/api/auth/user


### Logout
POST http://localhost:3030/api/auth/logout
