# Création d'une déclaration de type ets
# "id": "c1344a7e-64ea-4f9a-965d-bfd150110031",
POST http://localhost:3030/api/declarations
Content-Type: application/json

{
  "declarationType": "ets",
  "finesset": "350023883",
  // Champs génériques
  "date": "2021-07-16",
  "hour": "Matin (7h-12h)",
  "town": "Pointe-à-Pitre",
  "postalCode": "97110",
  "factGoods": {"Autres faits": ["Trafic de stupéfiants ou autre trafic dans l’établissement"]},
  "factPersons": {},
  "rCausePatients": [],
  "rCauseProfessionals": [],
  "rDiscords": [],
  "rLifeRules": [],
  "rFalsifications": [],
  "rDeficientCommunications": [],
  "rOthers": [],
  "rOthersPrecision": "",
  "rNotApparent": true,
  "description": "description for ets ",

  "victims": [
    {
      "type": "Accompagnant/Visiteur/Famille",
      "gender": "Masculin",
      "age": "- de 18 ans" ,
      "sickLeaveDays": 0,
      "hospitalizationDays": 0,
      "ITTDays": 0
    }
  ],
  "authors": [
    {
      "type": "Détenu",
      "gender": "Masculin",
      "age": "- de 18 ans"
    }
  ],
  "pursuit": {
    "type": "Plainte",
    "pursuitBy": [
      "L'établissement",
      "L'ordre"
    ]
  },
  "thirdParty": [
    "Personnel hospitalier",
    "Sapeurs-pompiers",
    ["Autre", "autre parties prenantes"]
  ],

  "location" : {
    "Dans quel service ?": "Addictologie",
    "Dans quel lieu précisément ?": "Bureau du personnel (médical ou non)"
  },

  // Champs spécifique deprecated
  "locationMain_deprecated": "Addictologie",
  "locationSecondary_deprecated": "Bureau du personnel (médical ou non)",

  // Champs génériques deprecated
  "fpSpokenViolences_deprecated": [],
  "fpSexualViolences_deprecated": [],
  "fpPsychologicalViolences_deprecated": [],
  "fpPhysicalViolences_deprecated": [],
  "fpOthers_deprecated": [],
  "fpNoRespects_deprecated": [],
  "fpGroups_deprecated": [],
  "fpDiscriminations_deprecated": [],
  "fgStealWithoutBreakins_deprecated": [],
  "fgStealWithBreakins_deprecated": [],
  "fgOthers_deprecated": ["Trafic de stupéfiants ou autre trafic dans l’établissement"],
  "fgGroups_deprecated": ["Autres faits"],
  "fgDeteriorations_deprecated": [],
  "factTypes_deprecated": ["Atteinte aux biens"],

  "thirdPartyIsPresent_deprecated": "Non",
  "thirdParty_deprecated": [],
  "pursuit_deprecated": "Non",
  "pursuitBy_deprecated": [],
  "victims_deprecated": [
    {
      "type": {
        "label": "Accompagnant/Visiteur/Famille",
        "value": "Accompagnant/Visiteur/Famille"
      },
      "gender": { "label": "Masculin", "value": "Masculin" },
      "age": { "label": "- de 18 ans", "value": "- de 18 ans" },
      "sickLeaveDays": 0,
      "hospitalizationDays": 0,
      "ITTDays": 0
    }
  ],
  "authors_deprecated": [
    {
      "discernmentTroublesIsPresent": "Non",
      "type": { "label": "Détenu", "value": "Détenu" },
      "gender": { "label": "Masculin", "value": "Masculin" },
      "age": { "label": "- de 18 ans", "value": "- de 18 ans" }
    }
  ]
}

### Décla de type ETS. KO car finesset n'existe pas dans la table ets

POST http://localhost:3030/api/declarations
Content-Type: application/json

{
  "declarationType": "ets",
  "finesset": "350023883",

  // Champs génériques
  "date": "2021-07-16",
  "hour": "Matin (7h-12h)",
  "town": "Pointe-à-Pitre",
  "postalCode": "97110",
  "factPersons": {},
  "factGoods": {"Autres faits" : ["Trafic de stupéfiants ou autre trafic dans l’établissement"]},
  "rCausePatients": [],
  "rCauseProfessionals": [],
  "rDiscords": [],
  "rLifeRules": [],
  "rFalsifications": [],
  "rDeficientCommunications": [],
  "rOthers": [],
  "rOthersPrecision": "",
  "rNotApparent": true,
  "description": "description for ets ",

  "victims": [
    {
      "type": "Accompagnant/Visiteur/Famille",
      "gender": "Masculin",
      "age": "- de 18 ans" ,
      "sickLeaveDays": 0,
      "hospitalizationDays": 0,
      "ITTDays": 0
    }
  ],
  "authors": [
    {
      "type": "Détenu",
      "gender": "Masculin",
      "age": "- de 18 ans"
    }
  ],
  "pursuit": {
    "type": "Plainte",
    "pursuitBy": [
      "L'établissement",
      "L'ordre"
    ]
  },
  "thirdParty": [
    "Personnel hospitalier",
    "Sapeurs-pompiers",
    ["Autre", "autre parties prenantes"]
  ],

  "location" : {
    "Dans quel service ?": "Addictologie",
    "Dans quel lieu précisément ?": "Bureau du personnel (médical ou non)"
  },

  // Champs spécifique deprecated
  "locationMain_deprecated": "Addictologie",
  "locationSecondary_deprecated": "Bureau du personnel (médical ou non)",

  // Champs génériques deprecated
  "fpSpokenViolences_deprecated": [],
  "fpSexualViolences_deprecated": [],
  "fpPsychologicalViolences_deprecated": [],
  "fpPhysicalViolences_deprecated": [],
  "fpOthers_deprecated": [],
  "fpNoRespects_deprecated": [],
  "fpGroups_deprecated": [],
  "fpDiscriminations_deprecated": [],
  "fgStealWithoutBreakins_deprecated": [],
  "fgStealWithBreakins_deprecated": [],
  "fgOthers_deprecated": ["Trafic de stupéfiants ou autre trafic dans l’établissement"],
  "fgGroups_deprecated": ["Autres faits"],
  "fgDeteriorations_deprecated": [],
  "factTypes_deprecated": ["Atteinte aux biens"],

  "thirdPartyIsPresent_deprecated": "Non",
  "thirdParty_deprecated": [],
  "pursuit_deprecated": "Non",
  "pursuitBy_deprecated": [],
  "victims_deprecated": [
    {
      "type": {
        "label": "Accompagnant/Visiteur/Famille",
        "value": "Accompagnant/Visiteur/Famille"
      },
      "gender": { "label": "Masculin", "value": "Masculin" },
      "age": { "label": "- de 18 ans", "value": "- de 18 ans" },
      "sickLeaveDays": 0,
      "hospitalizationDays": 0,
      "ITTDays": 0
    }
  ],
  "authors_deprecated": [
    {
      "discernmentTroublesIsPresent": "Non",
      "type": { "label": "Détenu", "value": "Détenu" },
      "gender": { "label": "Masculin", "value": "Masculin" },
      "age": { "label": "- de 18 ans", "value": "- de 18 ans" }
    }
  ]
}


#### Liberal declaration

POST http://localhost:3030/api/declarations
Content-Type: application/json

{
  "declarationType": "liberal",
  "finesset": "350023883",

  // Champs génériques
  "date": "2021-07-16",
  "hour": "Matin (7h-12h)",
  "town": "Pointe-à-Pitre",
  "postalCode": "97110",
  "factPersons": {},
  "factGoods": {"Autres faits" : ["Trafic de stupéfiants ou autre trafic dans l’établissement"]},
  "rCausePatients": [],
  "rCauseProfessionals": [],
  "rDiscords": [],
  "rLifeRules": [],
  "rFalsifications": [],
  "rDeficientCommunications": [],
  "rOthers": [],
  "rOthersPrecision": "",
  "rNotApparent": true,
  "description": "description for liberal",

  "victims": [
    {
      "type": "Accompagnant/Visiteur/Famille",
      "gender": "Masculin",
      "age": "- de 18 ans" ,
      "sickLeaveDays": 0,
      "hospitalizationDays": 0,
      "ITTDays": 0
    }
  ],
  "authors": [
    {
      "type": "Détenu",
      "gender": "Masculin",
      "age": "- de 18 ans"
    }
  ],
  "pursuit": {
    "type": "Plainte",
    "pursuitBy": [
      "L'établissement",
      "L'ordre"
    ]
  },
  "thirdParty": [
    "Personnel hospitalier",
    "Sapeurs-pompiers",
    ["Autre", "autre parties prenantes"]
  ],

  // Champs spécifiques
  "job": "Assistant dentaire",
  "declarantContactAgreement": true,

  "location" : {
    "Dans quel lieu précisément ?": "Cabinet individuel"
  },

  // Champs deprecated spécifiques
  "declarantContactAgreement_deprecated": "true",
  "location_deprecated": "",

  // champs deprecated génériques
  "fpSpokenViolences_deprecated": [],
  "fpSexualViolences_deprecated": [],
  "fpPsychologicalViolences_deprecated": [],
  "fpPhysicalViolences_deprecated": [],
  "fpOthers_deprecated": [],
  "fpNoRespects_deprecated": [],
  "fpGroups_deprecated": [],
  "fpDiscriminations_deprecated": [],
  "fgStealWithoutBreakins_deprecated": [],
  "fgStealWithBreakins_deprecated": [],
  "fgOthers_deprecated": ["Trafic de stupéfiants ou autre trafic dans l’établissement"],
  "fgGroups_deprecated": ["Autres faits"],
  "fgDeteriorations_deprecated": [],
  "factTypes_deprecated": ["Atteinte aux biens"],

  "thirdPartyIsPresent_deprecated": "Non",
  "thirdParty_deprecated": [],
  "pursuit_deprecated": "Non",
  "pursuitBy_deprecated": [],
  "victims_deprecated": [
    {
      "type": {
        "label": "Accompagnant/Visiteur/Famille",
        "value": "Accompagnant/Visiteur/Famille"
      },
      "gender": { "label": "Masculin", "value": "Masculin" },
      "age": { "label": "- de 18 ans", "value": "- de 18 ans" },
      "sickLeaveDays": 0,
      "hospitalizationDays": 0,
      "ITTDays": 0
    }
  ],
  "authors_deprecated": [
    {
      "discernmentTroublesIsPresent": "Non",
      "type": { "label": "Détenu", "value": "Détenu" },
      "gender": { "label": "Masculin", "value": "Masculin" },
      "age": { "label": "- de 18 ans", "value": "- de 18 ans" }
    }
  ]
}

### Liberal declaration with other location

POST http://localhost:3030/api/declarations
Content-Type: application/json

{
  // Champs spécifiques
  "declarationType": "liberal",
  "finesset": "350023883",
  "job": "Assistant dentaire",
  "declarantContactAgreement": true,
  "declarantContactAgreement_deprecated": "true",
  "location" : {
    "Dans quel lieu précisément ?": ["Autre", "pas très loin"]
  },
  "location_deprecated" : "pas très loin",

  // Champs génériques
  "date": "2021-07-16",
  "hour": "Matin (7h-12h)",
  "town": "Pointe-à-Pitre",
  "postalCode": "97110",
  "factPersons": {},
  "factGoods": {"Autres faits" : ["Trafic de stupéfiants ou autre trafic dans l’établissement"]},
  "rCausePatients": [],
  "rCauseProfessionals": [],
  "rDiscords": [],
  "rLifeRules": [],
  "rFalsifications": [],
  "rDeficientCommunications": [],
  "rOthers": [],
  "rOthersPrecision": "",
  "rNotApparent": true,

  "fpSpokenViolences_deprecated": [],
  "fpSexualViolences_deprecated": [],
  "fpPsychologicalViolences_deprecated": [],
  "fpPhysicalViolences_deprecated": [],
  "fpOthers_deprecated": [],
  "fpNoRespects_deprecated": [],
  "fpGroups_deprecated": [],
  "fpDiscriminations_deprecated": [],
  "fgStealWithoutBreakins_deprecated": [],
  "fgStealWithBreakins_deprecated": [],
  "fgOthers_deprecated": ["Trafic de stupéfiants ou autre trafic dans l’établissement"],
  "fgGroups_deprecated": ["Autres faits"],
  "fgDeteriorations_deprecated": [],
  "factTypes_deprecated": ["Atteinte aux biens"],
  "pursuit_deprecated": "Non",
  "victims_deprecated": [
    {
      "type": {
        "label": "Accompagnant/Visiteur/Famille",
        "value": "Accompagnant/Visiteur/Famille"
      },
      "gender": { "label": "Masculin", "value": "Masculin" },
      "age": { "label": "- de 18 ans", "value": "- de 18 ans" },
      "sickLeaveDays": 0,
      "hospitalizationDays": 0,
      "ITTDays": 0
    }
  ],
  "victims": [
    {
      "type": "Accompagnant/Visiteur/Famille",
      "gender": "Masculin",
      "age": "- de 18 ans",
      "sickLeaveDays": 0,
      "hospitalizationDays": 0,
      "ITTDays": 0
    }
  ],
  "authors_deprecated": [
    {
      "discernmentTroublesIsPresent": "Non",
      "type": { "label": "Détenu", "value": "Détenu" },
      "gender": { "label": "Masculin", "value": "Masculin" },
      "age": { "label": "- de 18 ans", "value": "- de 18 ans" }
    }
  ],
  "authors": [
    {
      "type": "Détenu",
      "gender": "Masculin",
      "age": "- de 18 ans"
    }
  ],
  "thirdPartyIsPresent_deprecated": "Non",
  "pursuitBy_deprecated": [],
  "thirdParty_deprecated": [],
  "description": "description for liberal"
}


### Liberal declaration with an id generated client side. KO car l'id existe déjà.
POST http://localhost:3030/api/declarations
Content-Type: application/json

{
  // Champs spécifiques
  "declarationType": "liberal",
  "finesset": "350023883",
  "job": "Assistant dentaire",
  "declarantContactAgreement": true,
  "declarantContactAgreement_deprecated": "true",
  "location" : {
    "Dans quel lieu précisément ?": ["Autre", "pas très loin"]
  },
  "location_deprecated" : "pas très loin",

  // Champs génériques
  "id": "ecdbced5-7fee-492b-af7e-cc58d527d50d",
  "date": "2021-07-16",
  "hour": "Matin (7h-12h)",
  "town": "Pointe-à-Pitre",
  "postalCode": "97110",
  "factPersons": {},
  "factGoods": {"Autres faits" : ["Trafic de stupéfiants ou autre trafic dans l’établissement"]},
  "rCausePatients": [],
  "rCauseProfessionals": [],
  "rDiscords": [],
  "rLifeRules": [],
  "rFalsifications": [],
  "rDeficientCommunications": [],
  "rOthers": [],
  "rOthersPrecision": "",
  "rNotApparent": true,

  "fpSpokenViolences_deprecated": [],
  "fpSexualViolences_deprecated": [],
  "fpPsychologicalViolences_deprecated": [],
  "fpPhysicalViolences_deprecated": [],
  "fpOthers_deprecated": [],
  "fpNoRespects_deprecated": [],
  "fpGroups_deprecated": [],
  "fpDiscriminations_deprecated": [],
  "fgStealWithoutBreakins_deprecated": [],
  "fgStealWithBreakins_deprecated": [],
  "fgOthers_deprecated": ["Trafic de stupéfiants ou autre trafic dans l’établissement"],
  "fgGroups_deprecated": ["Autres faits"],
  "fgDeteriorations_deprecated": [],
  "factTypes_deprecated": ["Atteinte aux biens"],

  "pursuit_deprecated": "Non",
  "victims_deprecated": [
    {
      "type": {
        "label": "Accompagnant/Visiteur/Famille",
        "value": "Accompagnant/Visiteur/Famille"
      },
      "gender": { "label": "Masculin", "value": "Masculin" },
      "age": { "label": "- de 18 ans", "value": "- de 18 ans" },
      "sickLeaveDays": 0,
      "hospitalizationDays": 0,
      "ITTDays": 0
    }
  ],
  "victims": [
    {
      "type": "Accompagnant/Visiteur/Famille",
      "gender": "Masculin",
      "age": "- de 18 ans",
      "sickLeaveDays": 0,
      "hospitalizationDays": 0,
      "ITTDays": 0
    }
  ],
  "authors_deprecated": [
    {
      "discernmentTroublesIsPresent": "Non",
      "type": { "label": "Détenu", "value": "Détenu" },
      "gender": { "label": "Masculin", "value": "Masculin" },
      "age": { "label": "- de 18 ans", "value": "- de 18 ans" }
    }
  ],
  "authors": [
    {
      "type": "Détenu",
      "gender": "Masculin",
      "age": "- de 18 ans"
    }
  ],
  "thirdPartyIsPresent_deprecated": "Non",
  "pursuitBy_deprecated": [],
  "thirdParty_deprecated": [],
  "description": "description for liberal"
}


### From formulaire

POST http://localhost:3030/api/declarations
Content-Type: application/json

{
  "declarationType":"liberal",
  "declarantContactAgreement":false,
  "declarantContactAgreement_deprecated":false,

  "postalCode":"91590",
  "job":"Audioprothésiste",
  "location_deprecated":"Cabinet individuel",
  "declarantContactAgreement_deprecated":"false",
  "date":"2021-07-20",
  "location":{
    "Dans quel lieu précisément ?":"Cabinet individuel"
  },
  "location_deprecated": "Cabinet individuel",
  "hour":"Matin (7h-12h)",
  "town":"D'Huison-Longueville",
  "factPersons": {},
  "factGoods": {"Autres faits" : ["Trafic de stupéfiants ou autre trafic dans l’établissement"]},
  "rCausePatients":[],
  "rCauseProfessionals":[],
  "rDiscords":[],
  "rLifeRules":[],
  "rFalsifications":[],
  "rDeficientCommunications":[],
  "rOthers":[],
  "rOthersPrecision":"",
  "rNotApparent":true,
  "fpSpokenViolences_deprecated":[],
  "fpSexualViolences_deprecated":[],
  "fpPsychologicalViolences_deprecated":[],
  "fpPhysicalViolences_deprecated":[],
  "fpOthers_deprecated":[],
  "fpNoRespects_deprecated":[],
  "fpGroups_deprecated":[],
  "fpDiscriminations_deprecated":[],
  "fgStealWithoutBreakins_deprecated":[],
  "fgStealWithBreakins_deprecated":[],
  "fgOthers_deprecated":["Trafic de stupéfiants ou autre trafic dans l’établissement"],
  "fgGroups_deprecated":["Autres faits"],
  "fgDeteriorations_deprecated":[],
  "factTypes_deprecated":["Atteinte aux biens"],

  "pursuit_deprecated":"Non",
  "victims_deprecated":[
    {
      "type":{
        "label":"Accompagnant/Visiteur/Famille",
        "value":"Accompagnant/Visiteur/Famille"
      },
      "gender":{
        "label":"Masculin",
        "value":"Masculin"
      },
      "age":{
        "label":"- de 18 ans",
        "value":"- de 18 ans"
      },
      "sickLeaveDays":0,
      "hospitalizationDays":0,
      "ITTDays":0
    }
  ],
  "victims":[
    {
      "type":"Accompagnant/Visiteur/Famille",
      "gender": "Masculin",
      "age": "- de 18 ans",
      "sickLeaveDays":0,
      "hospitalizationDays":0,
      "ITTDays":0
    }
  ],
  "authors_deprecated":[
    {
      "discernmentTroublesIsPresent":"Non",
      "type":{
        "label":"Accompagnant/Visiteur/Famille",
        "value":"Accompagnant/Visiteur/Famille"
      },
      "gender":{
        "label":"Masculin",
        "value":"Masculin"
      },
      "age":{
        "label":"- de 18 ans",
        "value":"- de 18 ans"
      }
    }
  ],
  "authors":[
    {
      "type": "Accompagnant/Visiteur/Famille",
      "gender": "Masculin",
      "age": "- de 18 ans"
    }
  ],
  "thirdPartyIsPresent_deprecated":"Non",
  "pursuitBy_deprecated":[],
  "thirdParty_deprecated":[],
  "description":"test"
}


### From formulaire ets
POST http://localhost:3030/api/declarations
Content-Type: application/json

{
  "declarationType":"ets",
  "finesset": "350023883",

  "postalCode":"78290",
  "locationMain_deprecated":"Addictologie",
  "locationSecondary_deprecated":"Véhicule (dans le cadre d’un transport de patients/résidents)",
  "location":{
    "Dans quel service ?":"Addictologie",
    "Dans quel lieu précisément ?":"Véhicule (dans le cadre d’un transport de patients/résidents)"
  },
  "declarantContactAgreement":null,
  "declarantContactAgreement_deprecated":null,

  "date":"2021-07-20",
  "hour":"Matin (7h-12h)",
  "town":"Croissy-sur-Seine",
  "factPersons": {},
  "factGoods": {"Autres faits" : ["Trafic de stupéfiants ou autre trafic dans l’établissement"]},
  "rCausePatients":[],
  "rCauseProfessionals":[],
  "rDiscords":[],
  "rLifeRules":[],
  "rFalsifications":[],
  "rDeficientCommunications":[],
  "rOthers":[],
  "rOthersPrecision":"",
  "rNotApparent":true,
  "fpSpokenViolences_deprecated":[],
  "fpSexualViolences_deprecated":[],
  "fpPsychologicalViolences_deprecated":[],
  "fpPhysicalViolences_deprecated":[],
  "fpOthers_deprecated":[],
  "fpNoRespects_deprecated":[],
  "fpGroups_deprecated":[],
  "fpDiscriminations_deprecated":[],
  "fgStealWithoutBreakins_deprecated":[],
  "fgStealWithBreakins_deprecated":[],
  "fgOthers_deprecated":["Trafic de stupéfiants ou autre trafic dans l’établissement"],
  "fgGroups_deprecated":["Autres faits"],
  "fgDeteriorations_deprecated":[],
  "factTypes_deprecated":["Atteinte aux biens"],

  "pursuit_deprecated":"Non",
  "victims_deprecated":[
    {
      "type":{
        "label":"Accompagnant/Visiteur/Famille",
        "value":"Accompagnant/Visiteur/Famille"
      },
      "gender":{
        "label":"Masculin",
        "value":"Masculin"
      },
      "age":{
        "label":"- de 18 ans",
        "value":"- de 18 ans"
      },
      "sickLeaveDays":0,
      "hospitalizationDays":0,
      "ITTDays":0
    }
  ],
  "victims":[
    {
      "type": "Accompagnant/Visiteur/Famille",
      "gender": "Masculin",
      "age": "- de 18 ans",
      "sickLeaveDays":0,
      "hospitalizationDays":0,
      "ITTDays":0
    }
  ],
  "authors_deprecated":[
    {
      "discernmentTroublesIsPresent":"Non",
      "type":{
        "label":"Accompagnant/Visiteur/Famille",
        "value":"Accompagnant/Visiteur/Famille"
      },
      "gender":{
        "label":"Masculin",
        "value":"Masculin"
      },
      "age":{
        "label":"- de 18 ans",
        "value":"- de 18 ans"
      }
    }
  ],
  "authors":[
    {
      "type": "Accompagnant/Visiteur/Famille",
      "gender": "Masculin",
      "age": "- de 18 ans"
    }
  ],
  "thirdPartyIsPresent_deprecated":"Non",
  "pursuitBy_deprecated":[],
  "thirdParty_deprecated":[],
  "description":"test"
}