@baseUrl = http://localhost:3030/api
@finesset = "957011804"

# Add a new ETS.
# @name etsCreation
POST {{baseUrl}}/ets
Content-Type: application/json

{
    "finesset": {{finesset}},
    "juridicStatus": "privé",
    "town": "West Cruz",
    "rs": "CHU West Cruz"
}

### List of all Ets.
GET {{baseUrl}}/ets?pageSize=4
Content-Type: application/json

###
PUT {{baseUrl}}/ets/{{etsCreation.response.body.data.id}}
Content-Type: application/json

{
    "id": "{{etsCreation.response.body.data.id}}",
    "finesset": "{{etsCreation.response.body.data.finesset}}",
    "juridicStatus": "{{etsCreation.response.body.data.juridicStatus}}",
    "town": "Vincennes",
    "rs": "CHU Vincennes"
}

###
DELETE  {{baseUrl}}/ets/{{etsCreation.response.body.data.id}}
Content-Type: application/json
