const { v4: uuid } = require("uuid")

// NB: all passwords are bcrypted and have the value "test"
exports.seed = function (knex) {
  return knex("declarations")
    .del()
    .then(function () {
      return knex("declarations").insert([
        {
          authors:
            '[{"age": {"label": "- de 18 ans", "value": "- de 18 ans"}, "type": {"label": "Accompagnant/Visiteur/Famille", "value": "Accompagnant/Visiteur/Famille"}, "gender": {"label": "Masculin", "value": "Masculin"}, "discernmentTroublesIsPresent": "Non"}]',
          created_at: "2021-05-04 13:33:44.988147+00",
          date: "2021-05-04",
          declarant_contact_agreement: "false",
          declarant_email: null,
          declarant_external_id: null,
          declarant_names: null,
          declarant_tel: null,
          declaration_type: "liberal",
          description: "test",
          ets_declared_by: null,
          ets_id: null,
          ets_location1: null,
          ets_location2: null,
          ets_moderated_by: null,
          ets_status: null,
          fact_types: '["Atteinte aux biens"]',
          fg_deteriorations: "[]",
          fg_groups: '["Autres faits"]',
          fg_others:
            '["Trafic de stupéfiants ou autre trafic dans l’établissement"]',
          fg_steal_with_breakins: "[]",
          fg_steal_without_breakins: "[]",
          fp_discriminations: "[]",
          fp_groups: "[]",
          fp_no_respects: "[]",
          fp_others: "[]",
          fp_physical_violences: "[]",
          fp_physical_violences_precision: null,
          fp_psychological_violences: "[]",
          fp_sexual_violences: "[]",
          fp_spoken_violences: "[]",
          hour: "Matin (7h-12h)",
          id: uuid(),
          job: "Assistant de service social",
          location: "Cabinet individuel",
          other_location: null,
          pursuit: "Non",
          pursuit_by: "[]",
          pursuit_precision: null,
          r_cause_patients: "[]",
          r_cause_professionals: "[]",
          r_deficient_communications: "[]",
          r_discords: "[]",
          r_falsifications: "[]",
          r_life_rules: "[]",
          r_not_apparent: true,
          r_others: "[]",
          r_others_precision: null,
          third_party: "[]",
          third_party_is_present: "Non",
          third_party_precision: null,
          town: "aze",
          victims:
            '[{"age": {"label": "- de 18 ans", "value": "- de 18 ans"}, "type": {"label": "Agent de sécurité-sûreté", "value": "Agent de sécurité-sûreté"}, "gender": {"label": "Masculin", "value": "Masculin"}, "ITTDays": 0, "sickLeaveDays": 0, "hospitalizationDays": 0}]',
        },
        {
          authors:
            '[{"age": {"label": "- de 18 ans", "value": "- de 18 ans"}, "type": {"label": "Accompagnant/Visiteur/Famille", "value": "Accompagnant/Visiteur/Famille"}, "gender": {"label": "Masculin", "value": "Masculin"}, "discernmentTroublesIsPresent": "Non"}]',
          created_at: "2021-05-04 13:34:53.18524+00",
          date: "2021-05-04",
          declarant_contact_agreement: null,
          declarant_email: null,
          declarant_external_id: null,
          declarant_names: null,
          declarant_tel: null,
          declaration_type: "ets",
          description: "test ets",
          ets_declared_by: null,
          ets_id: null,
          ets_location1: "Accueil Mère/enfant",
          ets_location2: "Bureau du personnel (médical ou non)",
          ets_moderated_by: null,
          ets_status: null,
          fact_types: '["Atteinte aux biens"]',
          fg_deteriorations: "[]",
          fg_groups: '["Autres faits"]',
          fg_others:
            '["Trafic de stupéfiants ou autre trafic dans l’établissement"]',
          fg_steal_with_breakins: "[]",
          fg_steal_without_breakins: "[]",
          fp_discriminations: "[]",
          fp_groups: "[]",
          fp_no_respects: "[]",
          fp_others: "[]",
          fp_physical_violences: "[]",
          fp_physical_violences_precision: null,
          fp_psychological_violences: "[]",
          fp_sexual_violences: "[]",
          fp_spoken_violences: "[]",
          hour: "Matin (7h-12h)",
          id: uuid(),
          job: null,
          location: null,
          other_location: null,
          pursuit: "Non",
          pursuit_by: "[]",
          pursuit_precision: null,
          r_cause_patients: "[]",
          r_cause_professionals: "[]",
          r_deficient_communications: "[]",
          r_discords: "[]",
          r_falsifications: "[]",
          r_life_rules: "[]",
          r_not_apparent: true,
          r_others: "[]",
          r_others_precision: null,
          third_party: "[]",
          third_party_is_present: "Non",
          third_party_precision: null,
          town: "aze",
          victims:
            '[{"age": {"label": "- de 18 ans", "value": "- de 18 ans"}, "type": {"label": "Accompagnant/Visiteur/Famille", "value": "Accompagnant/Visiteur/Famille"}, "gender": {"label": "Masculin", "value": "Masculin"}, "ITTDays": 0, "sickLeaveDays": 0, "hospitalizationDays": 0}]',
        },
        {
          authors:
            '[{"age": {"label": "+ de 18 ans", "value": "+ de 18 ans"}, "type": {"label": "Détenu", "value": "Détenu"}, "gender": {"label": "Masculin", "value": "Masculin"}, "discernmentTroublesIsPresent": "Non"}]',
          created_at: "2021-04-22 20:39:14.915979+00",
          date: "2021-04-22",
          declarant_contact_agreement: "false",
          declarant_email: null,
          declarant_external_id: null,
          declarant_names: null,
          declarant_tel: null,
          declaration_type: "liberal",
          description: "tes ",
          ets_declared_by: null,
          ets_id: null,
          ets_location1: null,
          ets_location2: null,
          ets_moderated_by: null,
          ets_status: null,
          fact_types: '["Atteinte aux biens"]',
          fg_deteriorations: "[]",
          fg_groups: '["Autres faits"]',
          fg_others:
            '["Trafic de stupéfiants ou autre trafic dans l’établissement"]',
          fg_steal_with_breakins: "[]",
          fg_steal_without_breakins: "[]",
          fp_discriminations: "[]",
          fp_groups: "[]",
          fp_no_respects: "[]",
          fp_others: "[]",
          fp_physical_violences: "[]",
          fp_physical_violences_precision: null,
          fp_psychological_violences: "[]",
          fp_sexual_violences: "[]",
          fp_spoken_violences: "[]",
          hour: "Matin (7h-12h)",
          id: uuid(),
          job: "Assistant dentaire",
          location: "Cabinet individuel",
          other_location: null,
          pursuit: "Non",
          pursuit_by: "[]",
          pursuit_precision: null,
          r_cause_patients: "[]",
          r_cause_professionals: "[]",
          r_deficient_communications: "[]",
          r_discords: "[]",
          r_falsifications: "[]",
          r_life_rules: "[]",
          r_not_apparent: true,
          r_others: "[]",
          r_others_precision: null,
          third_party: "[]",
          third_party_is_present: "Non",
          third_party_precision: null,
          town: "dg",
          victims:
            '[{"age": {"label": "- de 18 ans", "value": "- de 18 ans"}, "type": {"label": "Accompagnant/Visiteur/Famille", "value": "Accompagnant/Visiteur/Famille"}, "gender": {"label": "Masculin", "value": "Masculin"}, "ITTDays": 0, "sickLeaveDays": 0, "hospitalizationDays": 0}]',
        },
        {
          authors:
            '[{"age": {"label": "- de 18 ans", "value": "- de 18 ans"}, "type": {"label": "Accompagnant/Visiteur/Famille", "value": "Accompagnant/Visiteur/Famille"}, "gender": {"label": "Féminin", "value": "Féminin"}, "discernmentTroublesIsPresent": "Non"}]',
          created_at: "2021-04-21 14:54:11.242723+00",
          date: "2021-04-21",
          declarant_contact_agreement: null,
          declarant_email: null,
          declarant_external_id: null,
          declarant_names: null,
          declarant_tel: null,
          declaration_type: "ets",
          description: "erezrez",
          ets_declared_by: null,
          ets_id: null,
          ets_location1: "Addictologie",
          ets_location2: "Bureau du personnel (médical ou non)",
          ets_moderated_by: null,
          ets_status: null,
          fact_types: '["Atteinte aux biens"]',
          fg_deteriorations: "[]",
          fg_groups: '["Vol avec effraction"]',
          fg_others: "[]",
          fg_steal_with_breakins: '["Vol à main armée"]',
          fg_steal_without_breakins: "[]",
          fp_discriminations: "[]",
          fp_groups: "[]",
          fp_no_respects: "[]",
          fp_others: "[]",
          fp_physical_violences: "[]",
          fp_physical_violences_precision: null,
          fp_psychological_violences: "[]",
          fp_sexual_violences: "[]",
          fp_spoken_violences: "[]",
          hour: "Matin (7h-12h)",
          id: uuid(),
          job: null,
          location: null,
          other_location: null,
          pursuit: "Non",
          pursuit_by: "[]",
          pursuit_precision: null,
          r_cause_patients: "[]",
          r_cause_professionals: "[]",
          r_deficient_communications: "[]",
          r_discords: "[]",
          r_falsifications: "[]",
          r_life_rules: "[]",
          r_not_apparent: true,
          r_others: "[]",
          r_others_precision: null,
          third_party: "[]",
          third_party_is_present: "Non",
          third_party_precision: null,
          town: "ave",
          victims:
            '[{"age": {"label": "- de 18 ans", "value": "- de 18 ans"}, "type": {"label": "Accompagnant/Visiteur/Famille", "value": "Accompagnant/Visiteur/Famille"}, "gender": {"label": "Masculin", "value": "Masculin"}, "ITTDays": 0, "sickLeaveDays": 0, "hospitalizationDays": 0}]',
        },
      ])
    })
}
