root: true
overrides:
  - files: "*.js"
    extends:
      - "@socialgouv/eslint-config-react"
    rules:
      jsx-a11y/anchor-is-valid:
        - "error"
        - components: ["Link"]
          specialLink: ["hrefLeft", "hrefRight"]
          aspects: ["invalidHref", "preferButton"]
      react/prop-types: "warn"
      import/no-unresolved:
        - error
        - ignore:
            - "^@/"
  - files:
     - "*.ts"
     - "*.tsx"
    extends:
      - "@socialgouv/eslint-config-typescript"
    rules:
      import/no-unresolved:
        - error
        - ignore:
            - "^@/"