version: "3.6"
services:
  db:
    restart: always
    image: postgres:12.1
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U onvs"]
      interval: 5s
      timeout: 5s
      retries: 10
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
    ports:
      - 5435:5432
    volumes:
      - onvs-pgdata:/var/lib/postgresql/data
  app:
    restart: always
    build:
      context: .
      shm_size: 512M
      # env vars are handled by the .env file at the root and with .dotenv in the code
    ports:
      - 80:3030
    env_file:
      - .env

volumes:
  onvs-pgdata:
