kind: ConfigMap
apiVersion: v1
metadata:
  name: app-configmap
data:
  NODE_ENV: "production"
  PORT: "3000"
  NEXT_PUBLIC_SENTRY_TOKEN: "toto"
  NEXT_PUBLIC_SENTRY_DSN: "https://e70207cd7a2c4ecdb99849c212a964bf@sentry.fabrique.social.gouv.fr/40"
  NEXT_PUBLIC_MATOMO_URL: "https://matomo.fabrique.social.gouv.fr/"
  NEXT_PUBLIC_ONVS_API_TOKEN: "5e679014-eec3-4956-96f8-f084c616c54e"
  NEXT_PUBLIC_MATOMO_SITE_ID: "25"
  POSTGRES_SSL: "true"
  MAIL_FROM: "ONVS <noreply@fabrique.social.gouv.fr>"
